### ISSUE TITLE
Issue 1: User can view top 25 animes 

### ISSUE THREAD

**Issue by sarah-you** [sarah-you/myWatchList#1]
## ⚙️ Feature

- User can view Top 25 animes of 2023
- User can view detailed information on each anime listing
- User can watch YouTube trailer clips of the anime 
- User can access shortcut links to go watch the show

## 📐 Functionality

User can scroll through a selection of shows and click on ones that interest them and read more about them 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Desktop_ Home -- Anime List](https://user-images.githubusercontent.com/103456134/236067685-ecb6f69d-2c20-4a17-af77-e22181f26813.png)
![Desktop_ Ind List Modal](https://user-images.githubusercontent.com/103456134/236067689-1193187f-2331-487a-af2b-5cc136319fd0.png)
![Home -- Anime List](https://user-images.githubusercontent.com/103456134/236067690-53f64b0f-59cd-4307-b430-6757fff71c8a.png)
![Individual Listing -- Modal](https://user-images.githubusercontent.com/103456134/236067693-d0311bab-9244-4d42-97ba-3bd0037c5c0d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

**HTML**
- [x] h2 MyWatchList 
- [x] h3 Top 25 Anime List 2023
- [x] Div Container for page (1 row, 1 col-full) > each list item (25 rows)> wrap each line of text content

**JS**
  - [x] Create DOM tree for all data being pulled in from API & assign them accordingly
  - [x] Add 'click' Event Listener for each List (**See More** )
  - [x] Modal (class="hidden"), Modal Div 
  - [x] DOM inside Modal = title, rating, scored by, genre, eps, duration, synopsis, trailer, watch now
  - [x] Add 'click' Event Listener for 'close' button inside the modal 
  - [x] If user clicks close button, modal = hidden; should be displaying anime list

**CSS**
- [x] headings -- font-family: righteous (Google Fonts)
- [x] paragraph/text -- font-family: Montserrat (Google Fonts)
- [x] Logo #FB4D3D & Header (background: #FFFFFF)
- [x] Background #F0F0F0
- [x] modal -- hidden { display: none }
- [x] media queries rule set for desktop

**CLEAN UP**
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
