### ISSUE TITLE
Issue 2: User can add a show to their watchlist

### ISSUE THREAD

**Issue by sarah-you** [sarah-you/myWatchList#2]
## ⚙️ Feature

User can add a show to their own watchlist 

## 📐 Functionality

When user is browsing through the list of shows, user can click on each of the show listings and click the 'add' button to add that show to 'My List'

## 🖼️ Wireframe

![Desktop_ Home -- Anime List Pop Up Modal](https://user-images.githubusercontent.com/103456134/236071153-67381c95-ff88-4481-a9fa-ce9fca89d569.png)
![Desktop_ Home -- Anime List](https://user-images.githubusercontent.com/103456134/236071156-86ad4a6d-1935-49f4-851e-88dd3c0c35e7.png)
![Home -- Anime List](https://user-images.githubusercontent.com/103456134/236071157-a2845ac1-7fb3-4b1b-bf9a-334734d17049.png)
![Individual Listing -- Modal](https://user-images.githubusercontent.com/103456134/236071159-9462c0d7-4066-4afa-b272-4cdc9f9011c6.png)

## ✅ Task List

- [x] Set webpage display to mobile view size 
- [x] HTML: add div wrapping `main-page ` with 
`    <div data-view="main-page-list" id="main-page-list">`
- [x] HTML: add a div below the main anime-list page 
`    <div data-view="my-list" id="my-list" class="hidden">`
- [x] JS: in`renderList` function,` $modalAddBtn`, add `setAttribute('type', 'submit')`
- [x] JS: query select each view using getElementById for `main-page` and `my-list`
- [x] JS: viewswap function for each of the pages
![image](https://user-images.githubusercontent.com/103456134/235008193-4699d881-911b-44a0-932c-0e1bd3834706.png)
- [x] Create data.js file 
![image](https://user-images.githubusercontent.com/103456134/235011249-ef0b295e-0d40-4cd2-b852-6ebcf20728dc.png)
- [x] JS: 'click' event listener for the '+Add' button on the modal of each listing and in the code block, add viewswap(my-list) -- refer to image above for code 
- [x] JS: save the selected list item to local storage 
![image](https://user-images.githubusercontent.com/103456134/235009720-122495d6-ab3c-45b2-9bcc-6a12142fd334.png)

- [x] JS: render the selected show's `<li>` to the 'my-list' page with the same modal functions (copy $ol event listener openModal function)
- [x] JS: On `my-list` page's modals, `$modalAddBtn.setAttribute('class', 'hide-add modal-btn');`
- [x] CSS: rule set for `.hide { display: none;}`
- [x] the page should look pretty much the same as the list page, except only selected list items 
- [x] when list item is clicked, the same modal should pop up as the ones in the listings 
- [x] CSS: media queries to make it responsive for desktop
- [x] confirm that the design for both mobile and desktops match the one on live reloader 

**Clean Up**
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
