### ISSUE TITLE
Issue 3: User can add their own comments about the show on their watchlist

### ISSUE THREAD

**Issue by sarah-you** [sarah-you/myWatchList#3]
## ⚙️ Feature

User can add their own comments or notes about each of the show on their My List

## 📐 Functionality

After the user has added a show to their My List, they will be taken to their My List. Inside the My List page, there will be a textarea where user can input commentaries and save it for each show. 

## 🖼️ Wireframes

![Added to WatchList (before remove button)](https://user-images.githubusercontent.com/103456134/236084501-9dc17159-ed57-4bc3-8713-9f5b9a8c8389.png)
![Desktop_ Home -- My List with comments (before remove list button)](https://user-images.githubusercontent.com/103456134/236084504-3c3e2171-0f9c-441b-9a47-c2c01c35adbf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] set the live reloader screen to mobile display
- [x] within the list wrap div (so `appendchild to $listWrap`), create a div for comment section
- [x] within the comment div, create heading, [textarea](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea), and button (SAVE) 
- [x] placeholder text for textarea: delete comment by removing all text and clicking SAVE. 
to edit, click the comment box section and make your changes! Make sure to hit SAVE
- [x] for `textarea` and `button` formatting, refer to (http://jsfiddle.net/GwheP/)
- [x] to save the comments, create a new property in **data.js** file inside data obj `{comments: [];)}` 
- [x] check that the local storage updates with the new array added 
- [ ] create a 'click'` event listener `for SAVE `button ` so that once user clicks save, local storage stores the user input in the textarea (as is)
**![image](https://user-images.githubusercontent.com/103456134/236087800-5c54246d-04db-45c3-a9da-e08532b5cb11.png)**
- [ ] create a 'click'` event listener `for `textarea` box:
- [ ] the logic should work so that user can click the textarea at any given time and see their comment and update it (editing or removing all text) and hit save and the local storage updates to the newest comment
- [ ] on **layout.css** file, set media query rule so that on mobile, comment section is below the show and desktop, comment section is right side of the list 

**Clean Up**
  - [ ] Confirm that comment works by saving and removing content and saving again 
  - [ ] Remove all console logs.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
